In [2]:
#importing numpy library
import numpy as np

In [3]:
#1. Create a null vector of size 10 but the fifth value which is 1.
array=np.zeros(10)
array[4]=1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
#2. Create a vector with values ranging from 10 to 49.
arr=np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
array2=np.arange(0,9)
array2=array2.reshape(3,3)
print(array2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
arr1 = np.array([1,2,0,0,4,0])
print("original array") 
print(arr1) 
print("indices of non zero elements of the said array") 
index=np.where(arr1!=0)[0]
print(index)

original array
[1 2 0 0 4 0]
indices of non zero elements of the said array
[0 1 4]


In [20]:
#5. Create a 10x10 array with random values and find the minimum and maximum values
x = np.random.random((10,10))
xmin =x.min()
xmax = x.max()
print(xmin,xmax)

0.002659502731385377 0.9986726597243676


In [19]:
#6. Create a random vector of size 30 and find the mean value
Z = np.random.random(30)
m = Z.mean() 
print(m)

0.5483802751637322
